### ISSUE TITLE
FeatureRequest: Add the "h:sender" parameter to message.

### ISSUE THREAD

**Issue by evachon** [mailgun/mailgun-java#21]
Using the REST api directly it is possible to specify the sender using: "h:sender".

Would it be possible to add this parameter to com.mailgun.model.message.Message ?

**Comment by szagr** [comment]
You can use the `from` field for this.
`.from(custom value)`
or
`.from(EmailUtil.nameWithEmail(USER_NAME, EMAIL_FROM))`

**Comment by evachon** [comment]
Alright, thank you for your help.

**Comment by vkolida** [comment]
Using this mailgun-java library on my project I faced the issue similar to previously described on [stackoverflow](https://stackoverflow.com/questions/28401673/removing-on-behalf-of-when-sending-mail-using-mailgun) and explained at [Mailgun Help](https://help.mailgun.com/hc/en-us/articles/360012491394-Why-do-I-see-On-Behalf-Of-in-my-email-) page.

In a nutshell, the "On Behalf Of" notation is displaying as a From address in case of the mismatch between the domain used in the Sender field (mail.foo.com) and the domain used in the From field (foo.com):
`john=foo.com@mail.foo.com <john=foo.com@mail.foo.com> on behalf of; John Smith <john@foo.com>`

To solve the issue described above we need to set the `sender` property in the email header to the `from` address.

Using the `from` field: `.from(custom value)` or `.from(EmailUtil.nameWithEmail(USER_NAME, EMAIL_FROM))` is not the equivalent of setting `h:sender` parameter, as it only sets the From address.

So, adding the possibility to specify the `h:sender` parameter directly does make sense, at least to solve the "On Behalf Of" issue. Also, more general approach can be considered to add additional sending options/parameters by implementing `.addParameter(String name, Object value)` and/or `.addParameters(Map<String, Object> parameters)` methods within `com.mailgun.model.message.Message.MessageBuilder` to create corresponding `com.mailgun.model.message.Message`.

@szagr, would it be possible to extend mailgun-java library with additional sending options/parameters in the nearest release? It's quite crucial for my project, as we can keep using this handy mailgun-java library. Otherwise, having this limitation, we will have to search some alternative solutions.
