### ISSUE TITLE
Paging for mailing list members

### ISSUE THREAD

**Issue by arundaskd** [mailgun/mailgun-java#27]
For this API https://github.com/mailgun/mailgun-java#list-of-members, we can only limit the number of records. But in the response, there is an paging object and there is no function to get the next page data.

**Comment by vitalii-chornobryvyi-swi** [comment]
@arundaskd, thanks for raising this issue!
Sorry for the late reply.
The mentioned functionality was updated in the new release 1.1.0
Now you can get the first / last / next / previous page data by referencing this documentation: [List of members](https://github.com/mailgun/mailgun-java#list-of-members)

Please let us know If your issue is resolved and If we can close this ticket

**Comment by vitalii-chornobryvyi-swi** [comment]
the issue has been commented on, fixed and is closed due to the lack of an answer
