### ISSUE TITLE
Send Email with Template

### ISSUE THREAD

**Issue by hendisantika** [mailgun/mailgun-java#9]
I didn't see example that consist:
1. Send email with Thymeleaf HTML Template 
2. Send email with MailGun HTML Template
Can You provide the sample?

Thanks in advance

**Comment by szagr** [comment]
@hendisantika, thanks for your question.
 
Mailgun Java SDK is the only wrapper that uses Mailgun API
https://documentation.mailgun.com/en/latest/api_reference.html

As described in Mailgun documentation
https://documentation.mailgun.com/en/latest/api-templates.html#store-new-template
The template engine is used to render the template. This is valid only if the template parameter is provided. 
Currently, the Templates API supports only the **handlebars** engine.

What is Handlebars:
https://handlebarsjs.com/guide/#nested-input-objects

Because the Mailgun Java SDK does not have additional logic and only uses the Mailgun API, anything that works with curl or Postman should work with the Mailgun Java SDK.
If so, it is better to ask such questions directly in the Mailgun Help Center
https://help.mailgun.com/hc/en-us

**Comment by hendisantika** [comment]
OK. Thanks for the answer.
